=== scholasticus88/Learn_MSXML/Lesson3/IptXml.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.johnysparadise.ic.cz/pokus"
           elementFormDefault="qualified">
  <xs:element name="Database">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Movie" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Year" minOccurs="0">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="[1-9][0-9][0-9][0-9]" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Over18">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="yes" />
                    <xs:enumeration value="no" />
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="Actors">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Actor" minOccurs="0" maxOccurs="unbounded" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="medium" use="required">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:enumeration value="VHS" />
                  <xs:enumeration value="CD" />
                  <xs:enumeration value="DVD" />
                  <xs:enumeration value="BlueRay" />
                </xs:restriction>
              </xs:simpleType>
            </xs:attribute>
          </xs:complexType>
        </xs:element>       
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== scholasticus88/Learn_MSXML/Lesson3/IptXml.xml
<?xml version="1.0" encoding="utf-8"?>
<Database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.johnysparadise.ic.cz/pokus IptXml.xsd"
          xmlns="http://www.johnysparadise.ic.cz/pokus">
  <Movie medium="DVD">
    <Name>X Files</Name>
    <Year>1998</Year>
    <Over18>no</Over18>
    <Actors>
      <Actor>Gillian Anderson</Actor>
      <Actor>David Duchovny</Actor>
    </Actors>
  </Movie>
  <Movie medium="DVD">
    <Name>Golden Eye</Name>
    <Year>1999</Year>
    <Over18>no</Over18>
    <Actors>
      <Actor>Famke Jansenn</Actor>
    </Actors>
  </Movie>
  <Movie medium="DVD">
    <Name>5 Keys of Pleasure</Name>
    <Year>2008</Year>
    <Over18>yes</Over18>
    <Actors>
    </Actors>
  </Movie>
  <Movie medium="DVD">
    <Name>Entrapment</Name>
    <Year>1996</Year>
    <Over18>no</Over18>
    <Actors>
      <Actor>Catherine Zeta Jones</Actor>
    </Actors>
  </Movie>
  <Movie medium="DVD">
    <Name>Lord of the Rings</Name>
    <Year>2010</Year>
    <Over18>no</Over18>
    <Actors>
      <Actor>Frodo Pytlik</Actor>
    </Actors>
  </Movie>
</Database>
